#!/usr/bin/env python3
# -*- mode: python -*-

import argparse
import os
import re
import sys
import unittest

sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'tools'))

import tests.settings as test_settings

expected_tests = set((
    'backupstorage.backupstorage_tests.TestBasicBackup.test_add_duplicate_content',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_add_content_with_same_checksum',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_backup_end_time',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_backup_sequence',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_backup_start_time',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_checksum_timeline',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_get_content_info',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_get_content_reader',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_get_file_info',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_list_directory',
    'backupstorage.backupstorage_tests.TestBasicBackup.test_make_shadow_copy',
    'backupstorage.backupstorage_tests.TestBrokenUsage.test_add_two_files_with_same_path',
    'backupstorage.backupstorage_tests.TestBrokenUsage.test_open_storage_that_does_not_exist',
    'backupstorage.backupstorage_tests.TestCreateBasicBackup.test_create_backup',
    'backupstorage.backupstorage_tests.TestSingleStuff.test_add_content_data',
    'backupstorage.backupstorage_tests.TestSingleStuff.test_default_start_and_end_time',
    'backupstorage.backupstorage_tests.TestSingleStuff.test_get_most_recent_backup_when_no_backup_available',
    'backupstorage.backupstorage_tests.TestTwoBackups.test_backup_sequence',
    'backupstorage.backupstorage_tests.TestTwoBackups.test_get_backup_by_name',
    'backupstorage.backupstorage_tests.TestUtilities.test_make_path_from_contentid_in_new_storage',
    'backup.backupoperation_tests.TestBasicBackup.test_correct_files_are_backed_up',
    'backup.backupoperation_tests.TestBasicBackup.test_files_are_backed_up_with_correct_content',
    'backup.backupoperation_tests.TestBasicBackup.test_files_are_backed_up_with_correct_metadata',
    'backup.backupoperation_tests.TestBasicBackup.test_ignored_subtrees_are_not_traversed',
    'backup.backupoperation_tests.TestSecondBackup.test_changed_file_is_updated',
    'backup.backupoperation_tests.TestSecondBackup.test_changed_static_data_causes_error_to_be_reported',
    'backup.backupoperation_tests.TestSecondBackup.test_changed_static_data_is_backed_up',
    'backup.backupoperation_tests.TestSecondBackup.test_files_with_unchanged_mtime_and_size_are_assumed_same',
    'backup.backupoperation_tests.TestSecondBackup.test_move_static_data_to_nonstatic_causes_error_to_be_reported',
    'backup.backupoperation_tests.TestSecondBackup.test_moved_static_data_causes_no_error_to_be_reported',
    'backup.backupoperation_tests.TestSecondBackup.test_moved_static_data_is_backed_up',
    'backup.backupoperation_tests.TestSecondBackup.test_removed_static_data_causes_error_to_be_reported',
    'backup.backupoperation_tests.TestSecondBackup.test_removed_static_data_is_removed_in_new_backup',
    'backup.backupoperation_tests.TestSecondBackup.test_second_backup_includes_the_correct_files_content_and_metadata',
    'cli.cli_tests.TestSimpleStuff.test_commandline_backup',
    'cli.cli_tests.TestSimpleStuff.test_commandline_config',
    'cli.cli_tests.TestSimpleStuff.test_commandline_info',
    'cli.cli_tests.TestSimpleStuff.test_empty_commandline',
    'cli.cli_tests.TestSimpleStuff.test_create_default_services',
    'config.config_tests.TestFullConfig.test_backup_main_exists',
    'config.config_tests.TestFullConfig.test_path_handlers',
    'config.config_tests.TestSimpleConfig.test_backup_home',
    'config.config_tests.TestSimpleConfig.test_backup_home_storage',
    'config.config_tests.TestSimpleConfig.test_backup_home_source',
    'config.config_tests.TestSimpleConfig.test_backup_home_source_item_handlers',
    'config.config_tests.TestSimpleConfig.test_backup_home_source_subtree_handler_iterator',
    'config.config_tests.TestVarious.test_read_non_existing_file',
    'config.config_tests.TestVarious.test_read_two_simple_files',
    'config.config_tests.TestVarious.test_globs_work_in_intermediate_path_components',
    'config.config_tests.TestDeprecatedSimpleConfig.test_backup_home_storage',
    'database.database_tests.TestDatabaseWithManyBackups.test_backup_names_lists_all_backups',
    'database.database_tests.TestDatabaseWithManyBackups.test_get_most_recent_backup_before_scans_through_all_backups',
    'database.database_tests.TestDatabaseWithManyBackups.test_get_most_recent_backup_is_correct',
    'database.database_tests.TestDatabaseWithManyBackups.test_get_oldest_backup_after_scans_through_all_backups',
    'database.database_tests.TestDatabaseWithManyBackups.test_get_oldest_backup_is_correct',
    'database.database_tests.TestDatabaseWithManyBackups.test_get_backup_by_name_for_missing_backup_returns_none',
    'database.database_tests.TestDatabaseWithManyBackups.test_get_backup_by_name_returns_correct_backup',
    'database.database_tests.TestDatabaseWithOneBackup.test_add_content_item_adds_a_content_item',
    'database.database_tests.TestDatabaseWithOneBackup.test_backup_names_is_the_single_backup',
    'database.database_tests.TestDatabaseWithOneBackup.test_create_backup_file_returns_proper_object',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_all_contentinfos_with_checksum_returns_the_correct_info',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_all_contentinfos_with_missing_checksum_returns_none',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_backup_file_reader_for_name_returns_proper_file_reader',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_checksum_algorithm_is_sha256',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_checksum_algorithm_name_is_sha256',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_contentinfo_for_missing_cid_returns_none',
    'database.database_tests.TestDatabaseWithOneBackup.test_get_contentinfo_provides_the_correct_data',
    'database.database_tests.TestDatabaseWithOneBackup.test_iterate_contentids_provides_the_correct_cids',
    'database.database_tests.TestDatabaseWithOneBackup.test_most_recent_backup_before_after_the_backup_is_the_backup',
    'database.database_tests.TestDatabaseWithOneBackup.test_most_recent_backup_before_the_backup_is_none',
    'database.database_tests.TestDatabaseWithOneBackup.test_most_recent_backup_is_the_backup',
    'database.database_tests.TestDatabaseWithOneBackup.test_oldest_backup_after_before_the_backup_is_the_backup',
    'database.database_tests.TestDatabaseWithOneBackup.test_oldest_backup_after_the_backup_is_none',
    'database.database_tests.TestDatabaseWithOneBackup.test_oldest_backup_is_the_backup',
    'database.database_tests.TestDatabaseWithOneBackup.test_start_backup_returns_proper_object',
    'database.database_tests.TestCreateDatabase.test_create_database_and_backup',
    'database.database_tests.TestCreateDatabase.test_create_empty_database',
    'database.database_tests.TestCreateDatabaseFails.test_create_database_in_existing_directory_fails',
    'database.datafile_tests.TestDataFile.test_create_content_db',
    'database.datafile_tests.TestDataFile.test_create_multi_block_content_db',
    'database.datafile_tests.TestDataFile.test_create_main_directory_already_exists',
    'database.datafile_tests.TestDataFile.test_create_simple_backup',
    'database.datafile_tests.TestDataFile.test_create_simple_backup_without_commit_will_abort',
    'database.datafile_tests.TestDataFile.test_create_typical_main',
    'database.datafile_tests.TestDataFile.test_main_with_non_matching_checksum',
    'database.datafile_tests.TestDataFile.test_move_block_to_end',
    'database.datafile_tests.TestDataFile.test_open_backup_with_wrong_name',
    'database.datafile_tests.TestDataFile.test_open_main_does_not_exist',
    'database.datafile_tests.TestDataFile.test_raw_create_main_with_non_default_block_size',
    'database.datafile_tests.TestDataFile.test_raw_create_main_with_non_default_block_sum',
    'database.datafile_tests.TestDataFile.test_read_simple_backup',
    'database.datafile_tests.TestDataFile.test_read_main_with_non_default_block_size',
    'database.datafile_tests.TestDataFile.test_read_main_with_non_default_block_sum',
    'database.datafile_tests.TestDataFile.test_read_typical_content_db',
    'database.datafile_tests.TestDataFile.test_read_typical_main',
    'database.datafile_tests.TestDataFile.test_access_content_after_closing_it',
    'database.datafile_tests.TestDataFile.test_access_content_without_opening_it',
    'database.datafile_tests.TestDataFile.test_create_content_db_then_open_and_write_to_it',
    'database.datafile_tests.TestDataFile.test_get_and_open_content_when_it_does_not_exist',
    'database.datafile_tests.TestDataFile.test_get_unopened_content',
    'database.datafile_tests.TestDataFile.test_open_content_when_already_opened',
    'database.datafile_tests.TestDataFile.test_read_and_write_content_db',
    'database.datafile_tests.TestDataFile.test_create_simple_backup_with_special_files',
    'database.datafile_tests.TestDataFile.test_create_simple_backup_with_extra_file_data',
    'database.backupinfo_tests.TestBackupInfo.test_directory_listing_of_directory_path',
    'database.backupinfo_tests.TestBackupInfo.test_directory_listing_of_directory_path_to',
    'database.backupinfo_tests.TestBackupInfo.test_directory_listing_of_root_directory',
    'database.backupinfo_tests.TestBackupInfo.test_get_dir_info_for_directory',
    'database.backupinfo_tests.TestBackupInfo.test_get_end_time',
    'database.backupinfo_tests.TestBackupInfo.test_get_file_info_for_directory_should_be_none',
    'database.backupinfo_tests.TestBackupInfo.test_get_file_info_for_file',
    'database.backupinfo_tests.TestBackupInfo.test_get_start_time',
    'database.backupinfo_tests.TestBackupInfo.test_is_directory_for_directory_should_be_true',
    'database.backupinfo_tests.TestBackupInfo.test_is_directory_for_file_should_be_false',
    'database.backupinfo_tests.TestBackupInfo.test_is_file_for_directory_should_be_false',
    'database.backupinfo_tests.TestBackupInfo.test_is_file_for_file_should_be_true',
    'database.backupinfobuilder_tests.TestBackupInfoBuilder.test_build_a_simple_backup',
    'database.backupinfobuilder_tests.TestBackupInfoBuilder.test_build_a_simple_backup_with_extra_data',
    'database.backupinfobuilder_tests.TestBackupInfoBuilder.test_build_small_backup_should_create_small_file',
    'database.backupinfobuilder_tests.TestBackupInfoBuilder.test_invalid_utf8_in_file_names',
    'database.backupinfobuilder_tests.TestBackupInfoBuilder.test_multioctet_utf8_characters_in_file_names',
    'database.backupinfobuilder_tests.TestBackupInfoBuilder.test_various_timestamps_for_mtime',
    'database.contentdb_tests.TestContentDB.test_add_item',
    'database.contentdb_tests.TestContentDB.test_get_infos_for_checksum',
    'database.contentdb_tests.TestContentDB.test_info_for_cid',
    'database.contentdb_tests.TestContentDB.test_iterate_contentids',
    'database.contentdb_tests.TestContentDB.test_add_two_items_with_same_checksum',
    'acceptance.ebakup_application_tests.TestEbakupInvocation.test_run_ebakup_with_help_shows_help_message',
    'acceptance.ebakup_application_tests.TestEbakupInvocation.test_run_ebakup_without_args_exits_with_failure',
    'acceptance.ebakup_application_tests.TestEbakupInvocation.test_run_ebakup_without_args_shows_usage_message',
    'acceptance.ebakup_application_tests.TestEbakupLive.test_cached_state_after_second_backup',
    'acceptance.ebakup_application_tests.TestEbakupLive.test_making_first_backup',
    'acceptance.ebakup_application_tests.TestEbakupLive.test_making_second_backup',
    'acceptance.ebakup_application_tests.TestEbakupLive.test_shadowcopy_matches_tree',
    'acceptance.ebakup_application_tests.TestEbakupLive.test_verify_finds_some_problems',
    'filesys.filetree_tests.TestFileTree.test_has_file',
    'filesys.filetree_tests.TestFileTree.test_empty_tree_has_no_files',
    'filesys.filetree_tests.TestFileTree.test_files_in_dropped_subtree_are_gone',
    'filesys.filetree_tests.TestFileTree.test_tree_loaded_from_disk_has_expected_files',
    'filesys.filetree_tests.TestFileTree.test_tree_with_3_added_files_has_correct_file_content',
    'filesys.filetree_tests.TestFileTree.test_tree_with_3_added_files_has_those_files',
    'filesys.filetree_tests.TestFileTree.test_broken_utf8_file_name_bytes',
    'filesys.filetree_tests.TestFileTree.test_broken_utf8_file_name_string',
    'filesys.filetree_tests.TestFileTree.test_file_content_found_also_by_name_as_bytes',
    'filesys.filetree_tests.TestFileTree.test_change_file_changes_file_content',
    'filesys.filetree_tests.TestFileTree.test_copied_tree_has_the_same_files',
    'filesys.filetree_tests.TestFileTree.test_dropped_files_are_gone',
    'filesys.filetree_tests.TestFileTree.test_write_to_disk',
    'filesys.filetree_tests.TestFileTree.test_clone_tree_with_ignored_subpath',
    'filesys.filetree_tests.TestFileTree.test_cloned_tree_has_the_same_files',
    'filesys.filetree_tests.TestFileTree.test_cloned_tree_has_the_same_content',
    'filesys.filetree_tests.TestFileTree.test_copied_tree_has_the_same_content',
    'endtoend.system_live_tests.TestLocalFileSys.test_delete_file_at_path',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_filetype_pipe',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_filetype_regular',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_filetype_socket',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_filetype_symlink',
    'endtoend.system_live_tests.TestLocalFileSys.test_readsymlink',
    'endtoend.system_live_tests.TestLocalFileSys.test_readsymlink_on_file',
    'endtoend.system_live_tests.TestLocalFileSys.test_size_of_symlink',
    'config.glob_utils_tests.TestSimpleGlobs.test_does_not_have_common_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_has_common_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_invalid_globs',
    'config.glob_utils_tests.TestSimpleGlobs.test_range_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_range_non_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_simple_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_simple_non_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_special_chars',
    'config.glob_utils_tests.TestSimpleGlobs.test_trivial_matches',
    'config.glob_utils_tests.TestSimpleGlobs.test_valid_globs',
    'webui.http_handler_tests.TestTemplates.test_args_command',
    'webui.http_handler_tests.TestTemplates.test_start_time',
    'webui.http_server_tests.TestBasics.test_parallel_pipelined_requests',
    'webui.http_server_tests.TestBasics.test_pipelined_requests',
    'webui.http_server_tests.TestBasics.test_simple_request',
    'webui.http_server_tests.TestBasics.test_wakeup',
    'endtoend.system_cli_tests.TestFullSequenceOfOperations.test_everything',
    'endtoend.system_backupoperation_tests.TestSimpleBackup.test_backed_up_files_have_correct_checksum',
    'endtoend.system_backupoperation_tests.TestSimpleBackup.test_backed_up_files_have_correct_content',
    'endtoend.system_backupoperation_tests.TestSimpleBackup.test_backed_up_files_have_correct_metadata',
    'endtoend.system_backupoperation_tests.TestSimpleBackup.test_correct_files_backed_up',
    'endtoend.system_backupoperation_tests.TestSimpleBackup.test_single_backup_created',
    'endtoend.system_backupoperation_tests.TestSimpleBackup.test_start_end_times_sensible',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_existing_item',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_item_that_is_a_directory',
    'endtoend.system_live_tests.TestLocalFileSys.test_get_non_existing_item',
    'endtoend.system_tests.TestFullSequence.test_all',
    'cli.task_backup_tests.TestSimpleBackup.test_backup_from_and_to_correct_path',
    'cli.task_backup_tests.TestSimpleBackup.test_backup_handlers',
    'cli.task_backup_tests.TestSimpleBackup.test_backup_performed',
    'cli.task_backup_tests.TestSimpleBackup.test_backup_performed_to_existing_storage',
    'cli.task_backup_tests.TestSimpleBackup.test_backup_to_storage_with_correct_path',
    'cli.task_info_tests.TestInfoForEmptyConfig.test_output',
    'cli.task_info_tests.TestInfoForFullConfig.test_backup_mine_is_correct',
    'cli.task_info_tests.TestInfoForFullConfig.test_backup_mine_is_correct_partial',
    'cli.task_info_tests.TestInfoForFullConfig.test_configured_backups_are_listed',
    'cli.task_info_tests.TestInfoForFullConfig.test_toplevel_blocks',
    'cli.task_makeshadowtree_tests.TestMakeShadowTree.test_make_shadow_tree_at_existing_path',
    'cli.task_makeshadowtree_tests.TestMakeShadowTree.test_make_shadow_tree_for_empty_snapshot',
    'cli.task_makeshadowtree_tests.TestMakeShadowTree.test_make_shadow_tree_for_small_snapshot',
    'cli.task_makeshadowtree_tests.TestMakeShadowTree.test_make_shadow_tree_from_missing_snapshot',
    'cli.task_makeshadowtree_tests.TestMakeShadowTree.test_make_shadow_tree_with_special_file',
    'cli.task_sync_tests.TestSync.test_initial_sync_with_two_backups',
    'cli.task_sync_tests.TestSync.test_simple_initial_sync',
    'cli.task_sync_tests.TestSync.test_sync_with_common_backups',
    'cli.task_sync_tests.TestSync.test_sync_when_first_storage_has_one_extra_backup_it_is_copied_to_second_storage',
    'cli.task_verify_tests.TestTaskVerify.test_verify_empty_storage_is_ok',
    'cli.task_verify_tests.TestTaskVerify.test_verify_single_backup_storage_is_ok',
    'cli.task_verify_tests.TestTaskVerify.test_verify_single_backup_storage_with_corrupt_content',
    'cli.task_verify_tests.TestTaskVerify.test_verify_single_backup_storage_with_missing_content',
    'tools.tool_dump_db_file_tests.TestEarlyFormat.test_basic_backup_file',
    'tools.tool_dump_db_file_tests.TestEarlyFormat.test_content_file',
    'tools.tool_dump_db_file_tests.TestEarlyFormat.test_main_file',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_basic_backup_file',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_failed_block_checksum_first_data_block',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_failed_settings_checksum',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_trailing_garbage_in_data_block',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_trailing_garbage_in_settings_block',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_main_file',
    'tools.tool_dump_early_format_tests.TestSimpleDump.test_content_file',
    'verify.verifystorage_tests.TestVerifyStorage.test_verify_empty_storage_is_ok',
    'verify.verifystorage_tests.TestVerifyStorage.test_verify_single_backup_storage_is_ok',
    'verify.verifystorage_tests.TestVerifyStorage.test_verify_single_backup_storage_with_corrupt_content',
    'verify.verifystorage_tests.TestVerifyStorage.test_verify_single_backup_storage_with_missing_content',
    'database.valuecodecs_tests.TestCodecs.test_mtime_to_db_codec',
    'webui.webui_tests.TestWebUI.test_basic_404',
))
expected_test_count = len(expected_tests)

def find_tests():
    loader = unittest.defaultTestLoader
    tests = loader.discover('tests', '*_tests.py')
    return tests

def strip_prefix(string, prefix):
    if string.startswith(prefix):
        return string[len(prefix):]
    return string

def name_of_test(test):
    '''Returns None if 'test' is not a single test.
    '''
    try:
        name = test.id()
    except AttributeError:
        return None
    # When run from the main directory, the "tests." prefix is not
    # present, but when run from elsewhere it is.
    return strip_prefix(name, 'tests.')

def make_test_name_list(tests):
    names = []
    name = name_of_test(tests)
    if name:
        names.append(name)
    try:
        testiter = iter(tests)
    except TypeError:
        testiter = []
    for test in testiter:
        names += make_test_name_list(test)
    return names

def main_manual():
    tests = find_tests()
    results = unittest.TestResult()
    tests.run(results)
    print(results)
    print('Total tests run: ' + str(results.testsRun))
    print('Skipped: ' + str(len(results.skipped)))
    for item in results.skipped:
        print(item)
    print('Expected failures: ' + str(len(results.expectedFailures)))
    for item in results.expectedFailures:
        print(item)
    print('Unexpected successes: ' + str(len(results.unexpectedSuccesses)))
    for item in results.unexpectedSuccesses:
        print(item)
    print('Errors: ' + str(len(results.errors)))
    for item in results.errors:
        print(item)
    print('Failures: ' + str(len(results.failures)))
    for item in results.failures:
        print(item)
    if results.wasSuccessful():
        print('SUCCESS!')
    else:
        print('FAILURE!')

def filter_tests(test):
    if not args.filter:
        return test
    main = None
    name = name_of_test(test)
    if name and (name.startswith('unittest') or re.search(args.filter, name)):
        main = test
    try:
        testiter = iter(test)
    except TypeError:
        testiter = ()
    subs = []
    for subtest in testiter:
        sub = filter_tests(subtest)
        if sub:
            subs.append(sub)
    if subs:
        filtered = unittest.TestSuite(subs)
        if main:
            filtered.addTest(main)
        return filtered
    return main

def parse_args():
    global args
    ap = argparse.ArgumentParser(description='Run tests')
    ap.add_argument('--live', action='store_true',
                    help='Also run live tests, i.e. tests that may modify '
                    'the real file system')
    ap.add_argument('filter', nargs='?',
                    help='A regular expression. All tests whose names are '
                    'matched by the regular expression are included in the '
                    'test run.')
    args = ap.parse_args()

def main_texttestrunner():
    parse_args()
    if args.live:
        test_settings.enable_live_tests()
    tests = find_tests()
    test_names = make_test_name_list(tests)
    nameset = set(test_names)
    filtered = filter_tests(tests)
    if not filtered:
        print('No tests left after filtering.')
        return
    runner = unittest.TextTestRunner()
    results = runner.run(filtered)

    if tests == filtered:
        if results.testsRun != expected_test_count:
            print('ERROR: Expected {} tests, got {}'.format(expected_test_count, results.testsRun))
        if results.testsRun != len(test_names):
            print('ERROR: Different number of test names ({}) than tests run ({})'.
                  format(len(test_names), results.testsRun))
        if len(nameset) != len(test_names):
            print('ERROR: Only {} unique test names out of {}'.
                  format(len(nameset), len(test_names)))
        unexpected_tests = nameset - expected_tests
        if unexpected_tests:
            print('ERROR: {} unexpected tests:'.format(len(unexpected_tests)))
            for test in sorted(unexpected_tests):
                print("    '" + test + "',")
        missing_tests = expected_tests - nameset
        if missing_tests:
            print('ERROR: {} missing tests:'.format(len(missing_tests)))
            for test in sorted(missing_tests):
                print("    '" + test + "',")
    else:
        print('Filtered tests, {} tests run out of {}'.format(
                results.testsRun, len(test_names)))
        unexpected_tests = nameset - expected_tests
        if unexpected_tests:
            print('ERROR: {} unexpected tests:'.format(len(unexpected_tests)))
            for test in sorted(unexpected_tests):
                print("    '" + test + "',")


main_texttestrunner()
